In [8]:
import pandas as pd

# Read the CSV file with UTF-8 encoding
df = pd.read_csv(r'dataset/dataset_01.2/Job Posting.csv', encoding='ISO-8859-1')

In [9]:
df.head()

,Website Domain,Ticker,Job Opening Title,Job Opening URL,First Seen At,Last Seen At,Location,Location Data,Category,Seniority,...,Description,Salary,Salary Data,Contract Types,Job Status,Job Language,Job Last Processed At,O*NET Code,O*NET Family,O*NET Occupation Name
0,bosch.com,NaN,IN_RBAI_Assistant Manager_Dispensing Process E...,https://jobs.smartrecruiters.com/BoschGroup/74...,2024-05-29T19:59:45Z,2024-07-31T14:35:44Z,"Indiana, United States","[{""city"":null,""state"":""Indiana"",""zip_code"":nul...","engineering, management, support",manager,...,**IN\_RBAI\_Assistant Manager\_Dispensing Proc...,NaN,"{""salary_low"":null,""salary_high"":null,""salary_...",full time,closed,en,2024-08-02T14:47:55Z,43-1011.00,Office and Administrative Support,First-Line Supervisors of Office and Administr...
1,bosch.com,NaN,Professional Internship: Hardware Development ...,https://jobs.smartrecruiters.com/BoschGroup/74...,2024-05-04T01:00:12Z,2024-07-29T17:46:16Z,"Delaware, United States","[{""city"":null,""state"":""Delaware"",""zip_code"":nu...",internship,non_manager,...,**Professional Internship: Hardware Developmen...,NaN,"{""salary_low"":null,""salary_high"":null,""salary_...","full time, internship, m/f",closed,en,2024-07-31T17:50:07Z,17-2061.00,Architecture and Engineering,Computer Hardware Engineers
2,zf.com,NaN,Process Expert BMS Production,https://jobs.zf.com/job/Shenyang-Process-Exper...,2024-04-19T06:47:24Z,2024-05-16T02:25:08Z,China,"[{""city"":null,""state"":null,""zip_code"":null,""co...",engineering,non_manager,...,ZF is a global technology company supplying sy...,NaN,"{""salary_low"":null,""salary_high"":null,""salary_...",NaN,closed,en,2024-05-18T02:32:04Z,51-9141.00,Production,Semiconductor Processing Technicians
3,bosch.com,NaN,DevOps Developer with Python for ADAS Computin...,https://jobs.smartrecruiters.com/BoschGroup/74...,2024-08-16T10:20:37Z,2024-08-22T11:14:49Z,Romania,"[{""city"":null,""state"":null,""zip_code"":null,""co...","information_technology, software_development",non_manager,...,**DevOps Developer with Python for ADAS Comput...,NaN,"{""salary_low"":null,""salary_high"":null,""salary_...",full time,closed,en,2024-08-23T00:33:30Z,15-1252.00,Computer and Mathematical,Software Developers
4,bosch.com,NaN,Senior Engineer Sales - Video Systems and Solu...,https://jobs.smartrecruiters.com/BoschGroup/74...,2024-07-01T17:31:20Z,2024-08-01T05:11:33Z,India,"[{""city"":null,""state"":null,""zip_code"":null,""co...","engineering, sales",non_manager,...,**Senior Engineer Sales - Video Systems and So...,NaN,"{""salary_low"":null,""salary_high"":null,""salary_...",full time,closed,en,2024-08-02T19:03:16Z,41-9031.00,Sales and Related,Sales Engineers

In [10]:
# 1. Select the columns correctly using a list
selected_columns = df[['Job Opening Title', 'Description']]

# 2. Save to a new CSV file
selected_columns.to_csv('dataset/dataset_01.2/Job_Posting_Subset.csv', index=False)

print("File saved successfully!")

File saved successfully!

In [12]:
df_new = pd.read_csv('dataset/dataset_01.2/Job_Posting_Subset.csv')
len(df)

9919

In [ ]:
df_new.head()

,Job Opening Title,Description
0,IN_RBAI_Assistant Manager_Dispensing Process E...,**IN\_RBAI\_Assistant Manager\_Dispensing Proc...
1,Professional Internship: Hardware Development ...,**Professional Internship: Hardware Developmen...
2,Process Expert BMS Production,ZF is a global technology company supplying sy...
3,DevOps Developer with Python for ADAS Computin...,**DevOps Developer with Python for ADAS Comput...
4,Senior Engineer Sales - Video Systems and Solu...,**Senior Engineer Sales - Video Systems and So...

In [ ]:
df_new.columns = ['title', 'description']
df_new.to_csv('dataset/dataset_01.2/dataset01.2.csv', index=False)

print("Final dataset saved with new column names!")

Final dataset saved with new column names!

In [16]:
df = pd.read_csv("dataset/dataset_01.2/dataset01.2.csv")
df

,title,description
0,IN_RBAI_Assistant Manager_Dispensing Process E...,**IN\_RBAI\_Assistant Manager\_Dispensing Proc...
1,Professional Internship: Hardware Development ...,**Professional Internship: Hardware Developmen...
2,Process Expert BMS Production,ZF is a global technology company supplying sy...
3,DevOps Developer with Python for ADAS Computin...,**DevOps Developer with Python for ADAS Comput...
4,Senior Engineer Sales - Video Systems and Solu...,**Senior Engineer Sales - Video Systems and So...
...,...,...
9914,Apprentice Program,**Apprentice Program**\n\n\n* Full-time\n* Leg...
9915,"Environmental, Health and Safety (EHS) Special...","**Environmental, Health and Safety (EHS) Speci..."
9916,Technology & Quality Expert in Purchasing,**Technology & Quality Expert in Purchasing**\...
9917,Extracurricular Internship: Test Management (f...,**Extracurricular Internship: Test Management ...
9918,System Qualification Engineer,**Become our next FutureStarter**\n\n\n** Syst...